
name: Full Stack Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:

  backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot Project
        run: |
          cd courseenrollment
          mvn clean install

  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd cessystem
          npm install

      - name: Build React App
        run: |
          cd cessystem
          npm run build